### ISSUE TITLE
Problems using Kdenparse: Python errors

### ISSUE THREAD

**Issue by aberkl** [barry-lyndon/KdenParse#3]
Hi,

I tried converting a recent (kdenlive version=0.9.10) project to an EDL but I cannot get it working:
$ python ./kdenparse.py --edl berlinX.kdenlive

Traceback (most recent call last):
  File "./kdenparse.py", line 269, in <module>
    kp.createEdl()
  File "./kdenparse.py", line 147, in createEdl
    sourceLinks = self.linkReferences()
  File "./kdenparse.py", line 130, in linkReferences
    for i in self.getProducers():
  File "./kdenparse.py", line 123, in getProducers
    pDict[props.attributes["name"].value.replace(".","_")] = props.firstChild.data
AttributeError: 'NoneType' object has no attribute 'data'

I am running Ubuntu 14.04.1 LTS/Python 2.7.6. What am I doing wrong?

Unfortunately it seems I cannot attach the .kdenlive file here - I tried it after renaming to .png, maybe this works (download and rename to .kdenlive)... ![berlinx](https://cloud.githubusercontent.com/assets/9915206/5157998/cbb150f6-732d-11e4-8563-e130af9764ab.png)

Thanks a lot in advance from Germany,
Andreas

**Comment by mjacoulet** [comment]
Hello Andreas,

Any success with the script since 2014 ? I got exactly the same errors as you had.

Any comments from the builder ?

**Comment by aberkl** [comment]
Hi mjacoulet,

I didn't try it again, basically since my system didn't change. And no, no response from the developer.

Cheers, Andreas
